# Copyright 2020-2021 Ian Jackson and contributors to Otter
# SPDX-License-Identifier: AGPL-3.0-or-later
# There is NO WARRANTY.

[package]
name = "otter-api-tests"
authors = ["Ian Jackson <ijackson@chiark.greenend.org.uk>"]
license = "AGPL-3.0-or-later"

version = "0.0.1"
edition = "2018"

[dependencies]
otter = { path = ".." }

humantime = "2"
reqwest = "0.11"

# Repeated here because importing does not work properly
fehler = "1"
num-traits = "0.2"
serde = { version = "1", features = ["derive","rc"] }
structopt = "0.3"
strum = { version = "0.20", features = ['derive'] }

[lib]
name = "otter_api_tests"
path = "../apitest.rs"
