#!/bin/bash
set -e

tname="$1"; shift;
mkdir -p tmp

lname="$tname"
case "$1" in
--as-if=*)	lname="${1#--as-if=}";;
esac
lname="$lname.log"

target/debug/"$tname" "$@" 2>&1 | ts -s %.s >tmp/"$lname"
case "${PIPESTATUS[*]}" in
"0 0")	exit 0;
esac

fold -250 <tmp/"$lname" | tail -40 | sed -e "s/^/${lname%.log}: /"

exit 1
