#!/bin/bash
set -e

tname="$1"; shift;
mkdir -p tmp

lname="$tname"

for a in "$@"; do
	case "$a" in
	--test=*)	lname="${a#--test=}";;
	--as-if=*)	lname="${a#--as-if=}";;
	*)		break;;
	esac
done

lname="$lname.log"

target/debug/"$tname" "$@" 2>&1 | ts -s %.s >tmp/"$lname"
case "${PIPESTATUS[*]}" in
"0 0")	exit 0;
esac

fold -250 <tmp/"$lname" | tail -40 | sed -e "s/^/${lname%.log}: /"

exit 1
