#!/usr/bin/perl -w
use strict;

sub chk_repr ($) {
  my ($p) = @_;
  print "assert_eq($p, Bigfloats.pack(Bigfloats.unpack($p as any)));\n";
}

while (<>) {
  next unless m/^mod test/..0;
  my $l = $_;
  $l =~ s{bf\((\"[^"]+\")\)}{ chk_repr($1) }ge;
}
