#!/usr/bin/perl -w
# Copyright 2020 Ian Jackson
# SPDX-License-Identifier: AGPL-3.0-or-later
# There is NO WARRANTY.

use strict;
use Data::MessagePack;
use Data::Dumper;
$Data::Dumper::Sortkeys=1;
$/ = undef;
$!=0; $_ = <> // die $!;
my $mp = Data::MessagePack->new();
my $val = $mp->unpack($_);
print Dumper($val);
