merge_imports = false
overflow_delimited_expr = true
struct_field_align_threshold = 0
tab_spaces = 2
unstable_features = true
use_field_init_shorthand = true

# not in our rustfmt it seems:
# group_imports = "StdExternalCrate"
# preserve_closure_block_wrapping = true
# space_around_attr_eq = false
