# Copyright 2020-2021 Ian Jackson and contributors to Otter
# SPDX-License-Identifier: AGPL-3.0-or-later
# There is NO WARRANTY.

public_url = "http://localhost:18056"
http_port = 18056

base_dir = "."
command_socket = "command.socket"
bundled_sources = "target/bundled-sources"
save_dir = "."
template_dir = "templates"
wasm_dir = "target/packed-wasm"
libexec_dir = "target/debug"
usvg_bin = "target/release/usvg"

#save_dir = "/home/rustcargo/Rustup/Game/server"

#nwtemplate_dir = "/home/ian/Rustup/Game/server/nwtemplates"
#wasm_dir = "/home/rustcargo/Rustup/Game/server/target/packed-wasm"


#shapelibs = [ "/home/ian/Rustup/Game/server/library/*.toml" ]

[log]
global_level = 'debug'

[log.modules]

'hyper::server' = 'info'
"game::debugreader" = 'info'
#"game::updates" = 'trace'
