# Copyright 2020-2021 Ian Jackson and contributors to Otter
# SPDX-License-Identifier: AGPL-3.0-or-later
# There is NO WARRANTY.

# /volatile/rustcargo/Rustup/Game/server
# target/debug/daemon-otter ~ian/Rustup/Game/server/server-test-zealot.toml

public_url = "http://localhost:8000"
#sse_wildcard_url = "http://*.sse.localhost:8000"

save_dir = "/home/rustcargo/Rustup/Game/server"
command_socket = "/home/rustcargo/Rustup/Game/server/command.socket"
template_dir = "/home/ian/Rustup/Game/server/templates"
nwtemplate_dir = "/home/ian/Rustup/Game/server/nwtemplates"
bundled_sources = "/home/rustcargo/Rustup/Game/server/target/bundled-sources"
wasm_dir = "/home/rustcargo/Rustup/Game/server/target/packed-wasm"
libexec_dir = "/home/rustcargo/Rustup/Game/server/target/debug"
usvg_bin = "/home/rustcargo/Rustup/Game/server/target/release/usvg"

shapelibs = [ "/home/ian/Rustup/Game/server/library/*.toml" ]

[log]
global_level = 'debug'

[log.modules]
rocket = 'error'
_ = "error" # rocket
# ^ comment these two out to see Tera errors, *sigh*

'hyper::server' = 'info'
"game::debugreader" = 'info'
#"game::updates" = 'trace'
