# /volatile/rustcargo/Rustup/Game/server
# target/debug/server ~ian/Rustup/Game/server/server.toml

save_directory = "/home/ian/Rustup/Game/server/save"
template_dir = "/home/ian/Rustup/Game/server/templates"
