# /volatile/rustcargo/Rustup/Game/server
# target/debug/server ~ian/Rustup/Game/server/server.toml

# USER=rustcargo target/debug/otter --config ~ian/Rustup/Game/server/server.toml --scope-server reset --reset-table ~ian/Rustup/Game/server/demo/test.table.toml dummy  ~ian/Rustup/Game/server/demo/test.game.toml

save_directory = "/home/rustcargo/Rustup/Game/server"
template_dir = "/home/ian/Rustup/Game/server/templates"
bundled_sources = "/home/rustcargo/Rustup/Game/server/target/bundled-sources"

[log]
global_level = 'debug'

[log.modules]
'hyper::server' = 'info'
rocket = 'error'
_ = "error" # rocket
"game::debugreader" = 'info'
#"game::updates" = 'trace'
