# Copyright 2020-2021 Ian Jackson and contributors to Otter
# SPDX-License-Identifier: AGPL-3.0-or-later
# There is NO WARRANTY.

[package]
name = "otter-webdriver-tests"
authors = ["Ian Jackson <ijackson@chiark.greenend.org.uk>"]
license = "AGPL-3.0-or-later"

version = "0.0.1"
edition = "2018"

[dependencies]
otter = { path = ".." }

boolinator = "2"
env_logger = "0.8"
humantime = "2"
if_chain = "1"
itertools = "0.10"
log = "0.4"
libc = "0.2"
nix = "0.19"
ndarray = "0.14"
num-derive = "0.3"
num-traits = "0.2"
once_cell = "1"
parking_lot = "0.11"
regex = "1"
serde = { version = "1", features = ["derive","rc"] }
serde_json = "1"
structopt = "0.3"
strum = { version = "0.20", features = ['derive'] }
thirtyfour_sync = "0.22"
void = "1"
x11rb = "0.8"

# Repeated here because importing does not work properly
fehler = "1"

[lib]
name = "otter_webdriver_tests"
path = "../wdriver.rs"
