#!/bin/sh
set -e
self=jstest/run
src="${0%/$self}"
fail () { echo >&2 "$self: error: $*"; exit 1; }
[ "x$src/$self" = "x$0" ] || fail "mismatch $src/$self $0"

cd target/jstest
export NODE_PATH=.
ln -sf "$@" .

exec 3>run.js
sed >&3 <script.js '/^\/\/@@notest/,/^\/\/@@/d'
cat >&3 wasmtest.nodejs
exec 3>&-

nodejs run.js
