#!/bin/bash
set -e
self=jstest/run1
src="${0%/$self}"
fail () { echo >&2 "$self: error: $*"; exit 1; }
[ "x$src/$self" = "x$0" ] || fail "mismatch $src/$self $0"

t=${1##*/}
t=${t%%.*}

tmp=tmp/js-$t
rm -rf $tmp
mkdir -p $tmp
cd $tmp

ln -s ../../target/jstest/otter_wasm{.js,_bg.wasm} .

export NODE_PATH=.
ln -sf "$@" .

sed -n <$1 '
	/^\/\/ @@expect/,/^\/\/ @@end/ {
		s/^\/\/ //;
		/^@@/d;
		p;
	}
' >expect

exec 3>run.js
sed >&3 <script.js '/^\/\/@@notest/,/^\/\/@@/d'
cat >&3 wasmtest.nodejs
exec 3>&-

nodejs run.js >output

diff -u expect output
