# Copyright 2020-2021 Ian Jackson and contributors to Otter
# SPDX-License-Identifier: AGPL-3.0-or-later OR CC-BY-SA-3.0
# There is NO WARRANTY.

[group.lemon]
outline = "Circle"
size = [14]
orig_size = [533,533]
centre = [248, 257]

item_prefix = "example-"

files = """
lemon	-	a lemon
"""
