# Copyright 2020 Ian Jackson
# SPDX-License-Identifier: AGPL-3.0-or-later
# There is NO WARRANTY.

[package]
name = "otter-daemon"
authors = ["Ian Jackson <ijackson@chiark.greenend.org.uk>"]
license = "AGPL-3.0-or-later"

version = "0.0.1"
edition = "2018"

[[bin]]
name = "daemon-otter"
path = "main.rs"

[dependencies]
otter = { path = ".." }
otter-zcoord = { path = "../zcoord" }

fehler = "1"
serde = { version = "1", features = ["derive","rc"] }

rocket = { version = "^0.4.6", features=["sse"] }
rocket_cors = "0.5"

[dependencies.rocket_contrib]
version = "0.4"
default-features = false
features = ["tera_templates","helmet","json","serve"]
