# Copyright 2020-2021 Ian Jackson and contributors to Otter
# SPDX-License-Identifier: AGPL-3.0-or-later
# There is NO WARRANTY.

[package]
name = "otter-daemon"
authors = ["Ian Jackson <ijackson@chiark.greenend.org.uk>"]
license = "AGPL-3.0-or-later"

version = "0.0.1"
edition = "2018"

[[bin]]
name = "daemon-otter"
path = "main.rs"

[dependencies]
otter = { path = ".." }
otter-base = { path = "../base" }

uds = "0.2"
vecdeque-stableix = "1"

rocket = { version = "^0.4.6", features=["sse"] }
rocket_cors = "0.5"

# Repeated here because importing does not work properly
fehler = "1"
num-traits = "0.2"
serde = { version = "1", features = ["derive","rc"] }
serde_with = "1"
structopt = "0.3"
strum = { version = "0.20", features = ['derive'] }
thiserror = "1"

slotmap = { features = ['serde'], git = "https://github.com/ijackson/slotmap", branch="entry-return-stale-key" }
# ^ MR not yet reviewed

[dependencies.rocket_contrib]
version = "0.4"
default-features = false
features = ["tera_templates","helmet","json","serve"]
