
[[bin]]
name="daemon-otter"
path="main.rs"

[dependencies]
fehler="1"
num-traits="0.2"
rocket_cors="0.5"
serde_with="1"
structopt="0.3"

[dependencies.otter]
path=".."

[dependencies.otter-base]
path="../base"

[dependencies.rocket]
version="^0.4.6"
features=["sse"]

[dependencies.rocket_contrib]
default-features=false
version="0.4"
features=["tera_templates", "helmet", "json", "serve"]

[dependencies.serde]
version="1"
features=["derive", "rc"]

[dependencies.strum]
version="0.20"
features=["derive"]

[package]
edition="2018"
license="AGPL-3.0-or-later"
name="otter-daemon"
version="0.0.1"
authors=["Ian Jackson <ijackson@chiark.greenend.org.uk>"]
