# Copyright 2020-2021 Ian Jackson and contributors to Otter
# SPDX-License-Identifier: AGPL-3.0-or-later OR CC-BY-SA-3.0
# There is NO WARRANTY.

[scraper]
method = "cards-oxymoron"
spdx = "GPL-2.0-or-later"
filename_prefix = "cards/src/"
filename_suffix = ".gif"

[group.clubs]
item_prefix = "card-oxymoron-"
outline = "Rect"
size = [73, 97]
centre = [36.5, 48.5]
scale = 0.25

item_suffix = "-c"
sort = "card-playing-c_s"
desc_template = "the _desc of clubs"

occulted.method = "ByBack"
occulted.ilk = "card-back"

files = """
:		sort
2	-	02	two
3	-	03	three
4	-	04	four
5	-	05	five
6	-	06	six
7	-	07	seven
8	-	08	eight
9	-	09	nine
T	-	10	ten
J	-	11	jack
Q	-	12	queen
K	-	13	king
A	-	14	ace
"""

[group.clubs.back]
type = "Alias"
target = "card-back"

[group.diamonds]
inherit = "clubs"
item_suffix = "-d"
sort = "card-playing-d_s"
desc_template = "the _desc of diamonds"

[group.hearts]
inherit = "clubs"
sort = "card-playing-h_s"
item_suffix = "-h"
desc_template = "the _desc of hearts"

[group.spades]
inherit = "clubs"
sort = "card-playing-s_s"
item_suffix = "-s"
desc_template = "the _desc of spades"
