# Copyright 2020-2021 Ian Jackson and contributors to Otter and Simon Tatham
# SPDX-License-Identifier: AGPL-3.0-or-later OR CC-BY-SA-3.0
# There is NO WARRANTY.

format=2

[scraper]
method = "none"

[group.chess-board]
scale = 0.38
outline = "Rect"
files = """
chess-board	-	the chessboard
"""

[group.chess-misc]
size = [12]
item_prefix = "chess-"
outline = "Circle"
files = """
b-portal-blue	-	a blue portal piece belonging to black
w-portal-blue	-	a blue portal piece belonging to white
b-portal-orange	-	an orange portal piece belonging to black
w-portal-orange	-	an orange portal piece belonging to white
"""

[group.dice]
size = [21]
outline.shape = "Circle"
outline.size = [14]
item_prefix = "die-image-"
files = """
d6-_c	-	a _colour die image
"""

magic.item_prefix = "die-"
magic.template = """
image = !
type = "Die"
labels = 6
desc = "a _colour die"
occult.label = "?"
occult.ilk = "d6-_colour"
"""

[group.dice.colours.blue]
abbrev = "blue"
