# Copyright 2020-2021 Ian Jackson and contributors to Otter and Simon Tatham
# SPDX-License-Identifier: AGPL-3.0-or-later OR CC-BY-SA-3.0
# There is NO WARRANTY.

[scraper]
method = "none"

[group.chess-board]
size = [242, 246]
scale = 0.38
outline = "Square"
files = """
chess-board	-	the chessboard
"""

[group.chess-misc]
size = [32]
scale = 0.38
item_prefix = "chess-"
outline = "Circle"
files = """
b-portal-blue	-	a blue portal piece belonging to black
w-portal-blue	-	a blue portal piece belonging to white
b-portal-orange	-	an orange portal piece belonging to black
w-portal-orange	-	an orange portal piece belonging to white
"""
