# Copyright 2020 Ian Jackson
# SPDX-License-Identifier: AGPL-3.0-or-later OR CC-BY-SA-3.0
# There is NO WARRANTY.

[scraper]
method = "wikimedia"
site-title = "Wikimedia"
spdx = "CC-BY-SA-3.0"

licences = [ "Cc-by-sa-3.0", "GFDL|migration=relicense" ]
filename_suffix = ".svg"
url_prefix = "https://commons.wikimedia.org/wiki/File:"
url_suffix = "?action=raw"
data_url_prefix = "https://upload.wikimedia.org/wikipedia/commons/"
data_url_hashprefix = true

[group.chess]
outline = "Circle"
size = [9]
scale = 0.20
centre = [22.5, 22.5]
category = "chess"
item_prefix = "chess-"
stem_prefix = "Chess_"
files = """
w-B	blt45	a white bishop
"""

[group.chess-flip]
inherit = "chess"
flip = true
files = """
b-N	adt45	a black knight
"""
