# Copyright 2020 Ian Jackson
# SPDX-License-Identifier: AGPL-3.0-or-later OR CC-BY-SA-3.0
# There is NO WARRANTY.

[scraper]
method = "wikimedia"
site-title = "Wikimedia"
spdx = "CC-BY-SA-4.0"

licences = [ "Cc-by-sa-3.0", "Cc-by-sa-3.0-migrated", "cc-by-sa-4.0", "GFDL|migration=relicense", "cc-zero" ]
filename_suffix = ".svg"
url_prefix = "https://commons.wikimedia.org/wiki/File:"
url_suffix = "?action=raw"
data_url_prefix = "https://upload.wikimedia.org/wikipedia/commons/"
data_url_hashprefix = true

[group.chess]
outline = "Circle"
scale = 0.20
size = [45]
centre = [22.5, 22.5]
item_prefix = "chess-"
stem_prefix = "Chess_"

files = """
_c-P	plt45	a _colour pawn
_c-B	blt45	a _colour bishop
_c-R	rlt45	a _colour rook
_c-K	klt45	the _colour king
_c-Q	qlt45	the _colour queen

_c-elephant	elt45	a _colour elephant piece
_c-mann		Mlt45	a _colour Mann piece
"""

[group.chess.colours.white]
abbrev = "w"

[group.chess.colours.black]
abbrev = "b"
map = { "000000" = "ffffff", "ffffff" = "000000" }

[group.chess.colours."light blue"]
abbrev = "blue"
map = {"ffffff" = "05e2ff"}

[group.chess.colours."red"]
abbrev = "red"
map = {"ffffff" = "ff4805"}

[group.chess.colours."yellow"]
abbrev = "yellow"
map = {"ffffff" = "ffc505"}

[group.chess.colours."purple"]
abbrev = "purple"
map = {"ffffff" = "9305ff"}

[group.chess-flip]
inherit = "chess"
flip = true
files = """
_c-N	alt45	a _colour knight

_c-giraffe	Glt45	a _colour giraffe piece
_c-knight-king	Cet45	a _colour knight king piece
# ^ wikimedia calls these Centaurs
_c-ship		ship_slt45		a _colour ship piece
_c-zebra	Zlt45	a _colour zebra piece
"""

[group.chess-anomalous-filenames]
inherit = "chess"
stem_prefix = ""
files = """
_c-commoner	Commoner_Transparent		a _colour commoner piece
"""

[group.misc]
outline = "Square"
size = [448,326]
centre = [224, 163]
scale = 0.025
files = """
mgmt-library-load-marker   Box_with_polygons	a library load area marker
"""
