# Copyright 2020-2021 Ian Jackson and contributors to Otter
# SPDX-License-Identifier: AGPL-3.0-or-later OR CC-BY-SA-3.0
# There is NO WARRANTY.

[scraper]
method = "wikimedia"
site-title = "Wikimedia"
spdx = "CC-BY-SA-4.0 / AGPL-3.0-OR-LATER"

licences = [ "Cc-by-sa-3.0", "Cc-by-sa-3.0-migrated", "cc-by-sa-4.0", "GFDL|migration=relicense", "cc-zero", "LGPL", "PD-author|*" ]
filename_suffix = ".svg"
url_prefix = "https://commons.wikimedia.org/wiki/File:"
url_suffix = "?action=raw"
data_url_prefix = "https://upload.wikimedia.org/wikipedia/commons/"
data_url_hashprefix = true

[group.chess]
outline = "Circle"
scale = 0.20
size = [45]
item_prefix = "chess-"
stem_prefix = "Chess_"
occulted.method = "ByColour"
occulted.colour = "grey"

files = """
_c-P	plt45	a _colour pawn
_c-B	blt45	a _colour bishop
_c-R	rlt45	a _colour rook
_c-K	klt45	the _colour king
_c-Q	qlt45	the _colour queen

_c-elephant	elt45	a _colour elephant piece
_c-mann		Mlt45	a _colour Mann piece
"""

[group.chess.colours.white]
abbrev = "w"

[group.chess.colours.black]
abbrev = "b"
map = { "000000" = "cccccc", "ffffff" = "000000" }

[group.chess.colours."light blue"]
abbrev = "blue"
map = {"ffffff" = "04cbe5"}

[group.chess.colours."red"]
abbrev = "red"
map = {"ffffff" = "e64104", "000000" = "bbbbbb" }

[group.chess.colours."yellow"]
abbrev = "yellow"
map = {"ffffff" = "ffc505"}

[group.chess.colours."purple"]
abbrev = "purple"
map = {"ffffff" = "c105ff", "000000" = "bbbbbb" }

[group.chess.colours."grey"]
abbrev = "grey"
map = { "ffffff" = "888888" }

[group.chess-26]
inherit = "chess"
size = [26]
scale = 0.3461
files = """
_c-siege-engine	tlt26	a _colour siege engine piece
"""

[group.chess-flip]
inherit = "chess"
flip = true
files = """
_c-N	alt45	a _colour knight

_c-giraffe	Glt45	a _colour giraffe piece
_c-knight-king	Cet45	a _colour knight king piece
# ^ wikimedia calls these Centaurs
_c-ship		ship_slt45		a _colour ship piece
_c-zebra	Zlt45	a _colour zebra piece
"""

[group.chess-flip-26]
inherit = "chess-26"
flip = true
files = """
_c-flag		Blt26	a _colour flag piece
"""

[group.chess-flip-26-ship-adj]
inherit = "chess-flip-26"
flip = true
files = """
_c-cannon	Clt26	a _colour cannon piece
"""

[group.chess-anomalous-filenames]
inherit = "chess"
stem_prefix = ""
files = """
_c-commoner	Commoner_Transparent		a _colour commoner piece
"""

[group.chess-onecolour]
inherit = "chess"
colours = { }
files = """
# harlequin		put45		a black/white pawn
# ^ needs a grey LH edge really
"""

[group.misc]
outline = "Rect"
size = [448,326]
centre = [224, 163]
scale = 0.025
files = """
mgmt-library-load-marker   Box_with_polygons	a library load area marker
"""

[group.card-backs]
outline = "Rect"
size = [73, 97]

# sizes to match cards-oxymoron:
orig_size = [208, 303]
scale = 0.25

files = """
card-stripe-back-red	Card_back_03a	a card with a red-striped back
card-stripe-back-blue	Card_back_03b	a card with a blue-striped back
card-chequeredge-back	Card_back_04	a card (with a chequered edged back)
card-rainbow		Card_back_13	a rainbow card
"""

[group.cards-bellot]
outline = "Rect"
size = [73, 97]

# sizes to match cards-oxymoron:
orig_size = [167, 243]
scale = 0.25

files = """
card-bellot-joker-black		Joker_black_02	a joker
# card-bellot-joker-red		Joker_red_02	a joker
# ^ on wikimedia this file is unaccountably 60kb instead of 30kb
#   and furthermore a different size.  wat?
"""
