
[package]
name = "otter-wasm"
authors = ["Ian Jackson <ijackson@chiark.greenend.org.uk>"]
license = "AGPL-3.0-or-later"

version = "0.0.1"
edition = "2018"

[lib]
name = "otter_wasm"
path = "wasm.rs"
crate-type = ["cdylib"]

[dependencies]
otter-zcoord = { path = "../zcoord" }
wasm-bindgen = "0.2"
js-sys = "0.3"
fehler = "1"
thiserror = "1"
wee_alloc = "0.4"
#wee_alloc = { version = "0.4.5", optional = true }
