
[package]
name = "otter-wasm"
authors = ["Ian Jackson <ijackson@chiark.greenend.org.uk>"]
license = "AGPL-3.0-or-later"

version = "0.0.1"
edition = "2018"

[lib]
name = "otter_wasm"
path = "wasm.rs"
crate-type = ["cdylib"]

[dependencies]

otter-base = { path = "../base" }

console_error_panic_hook = "0.1"
js-sys = "0.3"
wasm-bindgen = "= 0.2.70"
wee_alloc = "0.4"

# Repeated here because importing does not work properly
fehler = "1"
