{# Copyright 2020-2021 Ian Jackson and contributors to Otter
   SPDX-License-Identifier: AGPL-3.0-or-later
   There is NO WARRANTY. #}

{% macro hand(pos, colour, lplace, edge="white", edge_width="0.75") %}
[[pieces]]
pos = {{pos}}
colour = "{{colour}}"
label.place = "{{lplace}}"
label.colour = "black"
type = "Hand"
edge = "{{edge}}"
edge_width = {{edge_width}}
shape.type = "Rect"
shape.xy = [93,25]
{% endmacro hand %}

{% macro deck(pos, lplace) %}
[[pieces]]
pos = {{pos}}
type = "PickupDeck"
faces = ["lightblue", "grey"]
edges = ["black", "white"]
label.colour = "black"
label.place = "{{lplace}}"
shape.type = "Rect"
shape.xy = [25,30]
{% endmacro deck %}


table_size = [300, 200]
table_colour = "#bbd"

[pcaliases.card-back]
type = "Lib"
lib = "wikimedia"
item = "card-plain-back-maroon"


{{ m::deck(pos=[136,115], lplace="BottomLeftOutside" )}}
{{ m::deck(pos=[162,115], lplace="BottomLeftOutside" )}}
{{ m::deck(pos=[150, 84], lplace="TopLeftOutside"    )}}

{{ m::hand(pos="[ 53,  25]", colour="brown" , lplace="BottomLeftOutside" )}}
{{ m::hand(pos="[150,  23]", colour="red"   , lplace="BottomLeftOutside" )}}
{{ m::hand(pos="[247,  25]", colour="orange", lplace="BottomLeftOutside" )}}
{{ m::hand(pos="[247,  70]", colour="yellow", lplace="BottomLeftOutside",
   edge="darkgrey", edge_width="1.0" )}}
{{ m::hand(pos="[247, 130]", colour="green" , lplace="TopLeftOutside"    )}}
{{ m::hand(pos="[247, 175]", colour="blue"  , lplace="TopLeftOutside"    )}}
{{ m::hand(pos="[150, 177]", colour="purple", lplace="TopLeftOutside"    )}}
{{ m::hand(pos="[ 53, 175]", colour="grey"  , lplace="TopLeftOutside"    )}}
{{ m::hand(pos="[ 53,  70]", colour="black" , lplace="BottomLeftOutside" )}}
{{ m::hand(pos="[ 53, 130]", colour="white" , lplace="TopLeftOutside"    ,
   edge="darkgrey", edge_width="1.0" )}}

[[pieces]]
pos = [150, 84]
type = "LibList"
lib = "wikimedia"
prefix = "card-"
items = [
 "bellot-joker-black", "bellot-joker-black", "rainbow",
 "bellot-joker-black", "bellot-joker-black", "rainbow",
 "bellot-joker-black", "bellot-joker-black", "rainbow",
]
posd = [0, 0]


[[pieces]]
pos = [150, 84]
type = "LibList"
lib = "cards-oxymoron"
prefix = "card-oxymoron-"
suffix = "-c"
items = [
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
]
posd = [0, 0]

[[pieces]]
pos = [150, 84]
type = "LibList"
lib = "cards-oxymoron"
prefix = "card-oxymoron-"
suffix = "-d"
items = [
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
]
posd = [0, 0]

[[pieces]]
pos = [150, 84]
type = "LibList"
lib = "cards-oxymoron"
prefix = "card-oxymoron-"
suffix = "-h"
items = [
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
]
posd = [0, 0]

[[pieces]]
pos = [150, 84]
type = "LibList"
lib = "cards-oxymoron"
prefix = "card-oxymoron-"
suffix = "-s"
items = [
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
]
posd = [0, 0]
