# Copyright 2020-2021 Ian Jackson and contributors to Otter
# SPDX-License-Identifier: AGPL-3.0-or-later
# There is NO WARRANTY.

table_size = [300, 200]
table_colour = "#bbd"

[pcaliases.card-back]
type = "Lib"
lib = "wikimedia"
item = "card-plain-back-maroon"


[[pieces]]
pos = [136,115]
type = "PickupDeck"
faces = ["lightblue", "grey"]
edges = ["black", "white"]
label.colour = "black"
label.place = "BottomLeftOutside"
shape.type = "Rect"
shape.xy = [25,30]

[[pieces]]
pos = [162,115]
type = "PickupDeck"
faces = ["lightblue", "grey"]
edges = ["black", "white"]
label.colour = "black"
label.place = "BottomLeftOutside"
shape.type = "Rect"
shape.xy = [25,30]

[[pieces]]
pos = [150,84]
type = "PickupDeck"
faces = ["lightblue", "grey"]
edges = ["black", "white"]
label.place = "TopLeftOutside"
label.colour = "black"
shape.type = "Rect"
shape.xy = [25,30]



[[pieces]]
pos = [150, 84]
type = "LibList"
lib = "wikimedia"
prefix = "card-"
items = [
 "bellot-joker-black", "bellot-joker-black", "rainbow",
 "bellot-joker-black", "bellot-joker-black", "rainbow",
]
posd = [0, 0]


[[pieces]]
pos = [150, 84]
type = "LibList"
lib = "cards-oxymoron"
prefix = "card-oxymoron-"
suffix = "-c"
items = [
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
]
posd = [0, 0]

[[pieces]]
pos = [150, 84]
type = "LibList"
lib = "cards-oxymoron"
prefix = "card-oxymoron-"
suffix = "-d"
items = [
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
]
posd = [0, 0]

[[pieces]]
pos = [150, 84]
type = "LibList"
lib = "cards-oxymoron"
prefix = "card-oxymoron-"
suffix = "-h"
items = [
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
]
posd = [0, 0]

[[pieces]]
pos = [150, 84]
type = "LibList"
lib = "cards-oxymoron"
prefix = "card-oxymoron-"
suffix = "-s"
items = [
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
    "2","3","4","5","6","7","8","9","T","J","Q","K","A",
]
posd = [0, 0]


[[pieces]]
pos = [50, 20]
colour = "brown"
label.place = "BottomLeftOutside"
label.colour = "black"

type = "Hand"
edge = "white"
edge_width = 0.75
shape.type = "Rect"
shape.xy = [97,25]

[[pieces]]
pos = [150, 14]
colour = "red"
label.place = "BottomLeftOutside"
label.colour = "black"

type = "Hand"
edge = "white"
edge_width = 0.75
shape.type = "Rect"
shape.xy = [97,25]

[[pieces]]
pos = [250, 20]
colour = "orange"
label.place = "BottomLeftOutside"
label.colour = "black"

type = "Hand"
edge = "white"
edge_width = 0.75
shape.type = "Rect"
shape.xy = [97,25]

[[pieces]]
pos = [250, 65]
colour = "yellow"
label.place = "BottomLeftOutside"
label.colour = "black"

type = "Hand"
edge = "darkgrey"
edge_width = 1.0
shape.type = "Rect"
shape.xy = [97,25]

[[pieces]]
pos = [250, 135]
colour = "green"
label.place = "TopLeftOutside"
label.colour = "black"

type = "Hand"
edge = "white"
edge_width = 0.75
shape.type = "Rect"
shape.xy = [97,25]

[[pieces]]
pos = [250, 180]
colour = "blue"
label.place = "TopLeftOutside"
label.colour = "black"

type = "Hand"
edge = "white"
edge_width = 0.75
shape.type = "Rect"
shape.xy = [97,25]

[[pieces]]
pos = [150, 186]
colour = "purple"
label.place = "TopLeftOutside"
label.colour = "black"

type = "Hand"
edge = "white"
edge_width = 0.75
shape.type = "Rect"
shape.xy = [97,25]

[[pieces]]
pos = [50, 180]
colour = "grey"
label.place = "TopLeftOutside"
label.colour = "black"

type = "Hand"
edge = "white"
edge_width = 0.75
shape.type = "Rect"
shape.xy = [97,25]

[[pieces]]
pos = [50, 65]
colour = "black"
label.place = "BottomLeftOutside"
label.colour = "black"

type = "Hand"
edge = "white"
edge_width = 0.75
shape.type = "Rect"
shape.xy = [97,25]

[[pieces]]
pos = [50, 135]
colour = "white"
label.place = "TopLeftOutside"
label.colour = "black"

type = "Hand"
edge = "darkgrey"
edge_width = 1.0
shape.type = "Rect"
shape.xy = [97,25]
