{# Copyright 2020-2021 Ian Jackson and contributors to Otter
   SPDX-License-Identifier: AGPL-3.0-or-later
   There is NO WARRANTY. #}

{% macro vanilla_officers() -%}
["R","N","B","Q","K","B","N","R"]
{% endmacro vanilla_officers %}

{% macro fairy_pieces() -%}
["commoner","elephant","knight-king","mann","zebra",
 "ship","giraffe","cannon"]
{% endmacro fairy_pieces -%}

table_size = [300, 200]
table_colour = "#bbd"

[[pieces]]
pos = [150,100]
type = "Lib"
lib = "edited"
item = "chess-board"
pinned = true

[[pieces]]
pos = [115,  135]
type = "LibList"
lib = "wikimedia"
prefix = "chess-w-"
items = {{ m::vanilla_officers() }}
posd = [10, 0]

[[pieces]]
pos = [115,  65]
type = "LibList"
lib = "wikimedia"
prefix = "chess-b-"
items = {{ m::vanilla_officers() }}
posd = [10, 0]

[[pieces]]
pos = [115, 125]
type = "Lib"
lib = "wikimedia"
item = "chess-w-P"
posd = [10, 0]
count = 8

[[pieces]]
pos = [115,  75]
type = "Lib"
lib = "wikimedia"
item = "chess-b-P"
posd = [10, 0]
count = 8


[[pieces]]
pos = [20, 75]
type = "Disc"
faces = ["#f88","#88f"]
posd = [10, 0]
diam = 7
count = 8

[[pieces]]
pos = [20, 85]
type = "Rect"
faces = ["yellow","#f4f"]
posd = [10, 0]
size = [7,7]
count = 8

[[pieces]]
pos = [20, 95]
type = "Rect"
faces = ["#333"]
posd = [10, 0]
size = [9,1]
count = 8

[[pieces]]
pos = [20, 100]
type = "Rect"
faces = ["#333"]
posd = [10, 0]
size = [9,1]
count = 8

[[pieces]]
pos = [17, 110]
type = "Rect"
faces = ["#333"]
posd = [5, 0]
size = [1,9]
count = 16

[[pieces]]
pos = [20,  125]
type = "LibList"
lib = "wikimedia"
prefix = "chess-w-"
items = {{ m::vanilla_officers() }}
posd = [10, 0]

[[pieces]]
pos = [20,  135]
type = "LibList"
lib = "wikimedia"
prefix = "chess-b-"
items = {{ m::vanilla_officers() }}
posd = [10, 0]

[[pieces]]
pos = [20, 145]
type = "Lib"
lib = "wikimedia"
item = "chess-w-P"
posd = [10, 0]
count = 4

[[pieces]]
pos = [60, 145]
type = "Lib"
lib = "wikimedia"
item = "chess-b-P"
posd = [10, 0]
count = 4

[[pieces]]
pos = [210, 55]
type = "LibList"
lib = "wikimedia"
prefix = "chess-blue-"
items = ["K","Q","R","R","B","B","N","N"]
posd = [10, 0]

[[pieces]]
pos = [210, 65]
type = "LibList"
lib = "wikimedia"
prefix = "chess-yellow-"
items = ["K","Q","R","R","B","B","N","N"]
posd = [10, 0]

[[pieces]]
pos = [210, 75]
type = "LibList"
lib = "wikimedia"
prefix = "chess-red-"
items = ["K","Q","R","R","B","B","N","N"]
posd = [10, 0]

[[pieces]]
pos = [210, 45]
type = "LibList"
lib = "wikimedia"
prefix = "chess-purple-"
items = ["K","Q","R","R","B","B","N","N"]
posd = [10, 0]

[[pieces]]
pos = [205, 125]
type = "LibList"
lib = "wikimedia"
prefix = "chess-w-"
items = {{ m::fairy_pieces() }}
posd = [10, 0]

[[pieces]]
pos = [205, 135]
type = "LibList"
lib = "wikimedia"
prefix = "chess-w-"
items = {{ m::fairy_pieces() }}
posd = [10, 0]

[[pieces]]
pos = [205, 145]
type = "LibList"
lib = "wikimedia"
prefix = "chess-b-"
items = {{ m::fairy_pieces() }}
posd = [10, 0]

[[pieces]]
pos = [205, 155]
type = "LibList"
lib = "wikimedia"
prefix = "chess-b-"
items = {{ m::fairy_pieces() }}
posd = [10, 0]

[[pieces]]
pos = [20, 60]
type = "Hand"
edge = "white"
colour = "grey"
shape.type = "Rect"
shape.xy = [20,10]


[[pieces]]
# 1
shape.xy = [20,6]
pos = [50, 58]
type = "PlayerLabel"
colour = "lightgrey"
edge = "white"
shape.type = "Rect"
label.place = "BottomLeft"
label.colour = "black"

[[pieces]]
# 2
shape.xy = [20,6]
pos = [51, 59]
type = "PlayerLabel"
colour = "lightgrey"
edge = "white"
shape.type = "Rect"
label.place = "BottomLeft"
label.colour = "black"

[[pieces]]
# 3
shape.xy = [20,6]
pos = [52, 60]
type = "PlayerLabel"
colour = "lightgrey"
edge = "white"
shape.type = "Rect"
label.place = "BottomLeft"
label.colour = "black"

[[pieces]]
# 4
shape.xy = [20,6]
pos = [53, 61]
type = "PlayerLabel"
colour = "lightgrey"
edge = "white"
shape.type = "Rect"
label.place = "BottomLeft"
label.colour = "black"

[[pieces]]
# 5
shape.xy = [20,6]
pos = [54, 62]
type = "PlayerLabel"
colour = "lightgrey"
edge = "white"
shape.type = "Rect"
label.place = "BottomLeft"
label.colour = "black"

[[pieces]]
# 6
shape.xy = [20,6]
pos = [60, 57]
type = "PlayerLabel"
colour = "lightgrey"
edge = "white"
shape.type = "Rect"
label.place = "BottomLeft"
label.colour = "black"

[[pieces]]
# 7
shape.xy = [20,6]
pos = [61, 58]
type = "PlayerLabel"
colour = "lightgrey"
edge = "white"
shape.type = "Rect"
label.place = "BottomLeft"
label.colour = "black"

[[pieces]]
# 8
shape.xy = [20,6]
pos = [62, 59]
type = "PlayerLabel"
colour = "lightgrey"
edge = "white"
shape.type = "Rect"
label.place = "BottomLeft"
label.colour = "black"

[[pieces]]
# 9
shape.xy = [20,6]
pos = [63, 60]
type = "PlayerLabel"
colour = "lightgrey"
edge = "white"
shape.type = "Rect"
label.place = "BottomLeft"
label.colour = "black"

[[pieces]]
# 10
shape.xy = [20,6]
pos = [64, 61]
type = "PlayerLabel"
colour = "lightgrey"
edge = "white"
shape.type = "Rect"
label.place = "BottomLeft"
label.colour = "black"


[[pieces]]
pos = [240, 100]
type = "ChessClock"
time = 900
per_move = 30
