# Copyright 2020 Ian Jackson
# SPDX-License-Identifier: AGPL-3.0-or-later
# There is NO WARRANTY.

table_size = [300, 200]
table_colour = "#bbd"

[[pieces]]
pos = [150,100]
type = "Lib"
lib = "edited"
item = "chess-board"
pinned = true

[[pieces]]
pos = [115,  135]
type = "LibList"
lib = "wikimedia"
prefix = "chess-w-"
items = ["R","N","B","Q","K","B","N","R"]
posd = [10, 0]

[[pieces]]
pos = [115,  65]
type = "LibList"
lib = "wikimedia"
prefix = "chess-b-"
items = ["R","N","B","Q","K","B","N","R"]
posd = [10, 0]

[[pieces]]
pos = [115, 125]
type = "Lib"
lib = "wikimedia"
item = "chess-w-P"
posd = [10, 0]
count = 8

[[pieces]]
pos = [115,  75]
type = "Lib"
lib = "wikimedia"
item = "chess-b-P"
posd = [10, 0]
count = 8


[[pieces]]
pos = [20, 75]
type = "Disc"
faces = ["#f88","#88f"]
posd = [10, 0]
diam = 7
count = 8

[[pieces]]
pos = [20, 85]
type = "Square"
faces = ["yellow","#f4f"]
posd = [10, 0]
size = [7,7]
count = 8

[[pieces]]
pos = [20, 95]
type = "Square"
faces = ["#333"]
posd = [10, 0]
size = [9,1]
count = 8

[[pieces]]
pos = [20, 100]
type = "Square"
faces = ["#333"]
posd = [10, 0]
size = [9,1]
count = 8

[[pieces]]
pos = [17, 110]
type = "Square"
faces = ["#333"]
posd = [5, 0]
size = [1,9]
count = 16

[[pieces]]
pos = [20,  125]
type = "LibList"
lib = "wikimedia"
prefix = "chess-w-"
items = ["R","N","B","Q","K","B","N","R"]
posd = [10, 0]

[[pieces]]
pos = [20,  135]
type = "LibList"
lib = "wikimedia"
prefix = "chess-b-"
items = ["R","N","B","Q","K","B","N","R"]
posd = [10, 0]

[[pieces]]
pos = [20, 145]
type = "Lib"
lib = "wikimedia"
item = "chess-w-P"
posd = [10, 0]
count = 4

[[pieces]]
pos = [60, 145]
type = "Lib"
lib = "wikimedia"
item = "chess-b-P"
posd = [10, 0]
count = 4

[[pieces]]
pos = [210, 55]
type = "LibList"
lib = "wikimedia"
prefix = "chess-blue-"
items = ["K","Q","R","R","B","B","N","N"]
posd = [10, 0]

[[pieces]]
pos = [210, 65]
type = "LibList"
lib = "wikimedia"
prefix = "chess-yellow-"
items = ["K","Q","R","R","B","B","N","N"]
posd = [10, 0]

[[pieces]]
pos = [210, 75]
type = "LibList"
lib = "wikimedia"
prefix = "chess-red-"
items = ["K","Q","R","R","B","B","N","N"]
posd = [10, 0]

[[pieces]]
pos = [210, 85]
type = "LibList"
lib = "wikimedia"
prefix = "chess-purple-"
items = ["K","Q","R","R","B","B","N","N"]
posd = [10, 0]

[[pieces]]
pos = [205, 115]
type = "LibList"
lib = "wikimedia"
prefix = "chess-w-"
items = ["commoner","elephant","knight-king","mann","zebra",
	 "ship","giraffe","cannon","flag"]
posd = [10, 0]

[[pieces]]
pos = [205, 125]
type = "LibList"
lib = "wikimedia"
prefix = "chess-w-"
items = ["commoner","elephant","knight-king","mann","zebra",
	 "ship","giraffe","cannon","flag"]
posd = [10, 0]

[[pieces]]
pos = [205, 135]
type = "LibList"
lib = "wikimedia"
prefix = "chess-b-"
items = ["commoner","elephant","knight-king","mann","zebra",
	"ship","giraffe","cannon","flag"]
posd = [10, 0]

[[pieces]]
pos = [205, 145]
type = "LibList"
lib = "wikimedia"
prefix = "chess-b-"
items = ["commoner","elephant","knight-king","mann","zebra",
	 "ship","giraffe","cannon","flag"]
posd = [10, 0]
