# Copyright 2020-2021 Ian Jackson and contributors to Otter
# SPDX-License-Identifier: AGPL-3.0-or-later
# There is NO WARRANTY.

timezone = "Europe/London"

#players = [ { account_glob = "server:*" } ]

[links]
Voice = "https://jitsi.example.com/initial"

[[players]]
account_glob = "server:*"

# USER=rustcargo  target/debug/otter --config ~ian/Rustup/Game/server/server-test-zealot.toml --account server: reset --reset-table ~ian/Rustup/Game/server/specs/test.table.toml server::dummy  ~ian/Rustup/Game/server/specs/demo.game.toml

# USER=rustcargo target/debug/otter --config ~ian/Rustup/Game/server/server-test-zealot.toml --super --fixed-token kmqAKPwK4TfReFjMor8MJhdRPBcwIBpe --account server:alice join-game server::dummy

# USER=rustcargo target/debug/otter --config ~ian/Rustup/Game/server/server-test-zealot.toml --account server: library-list wikimedia \*

# USER=rustcargo target/debug/otter --config ~ian/Rustup/Game/server/server-test-zealot.toml --account server: library-add server::dummy wikimedia chess-\*

# USER=rustcargo target/debug/otter --config ~ian/Rustup/Game/server/server-test-zealot.toml --account server:carol join-game server::dummy
