[[players]]
nick = "alice"
access = { deliver = "FixedToken", token = "kmqAKPwK4TfReFjMor8MJhdRPBcwIBpe" }

[[players]]
nick = "bob"
access = { deliver = "FixedToken", token = "ccg9kzoTh758QrVE1xMY7BQWB36dNJTx" }
