# Copyright 2020 Ian Jackson
# SPDX-License-Identifier: AGPL-3.0-or-later
# There is NO WARRANTY.

timezone = "Europe/London"

#players = [ { account_glob = "server:*" } ]

[[players]]
account_glob = "server:*"

#nick = "alice"
#access = "FixedToken"
#token = "kmqAKPwK4TfReFjMor8MJhdRPBcwIBpe"

#[[players]]
#nick = "bob"
#access = "FixedToken"
#token = "ccg9kzoTh758QrVE1xMY7BQWB36dNJTx"
