# Copyright 2020 Ian Jackson
# SPDX-License-Identifier: AGPL-3.0-or-later
# There is NO WARRANTY.

table_size = [300, 100]

[[pieces]]
pos = [90,80]
type = "Disc"
diam = 20
faces = ["red","grey"]

[[pieces]]
pos = [90, 60]
type = "Square"
size = [20]
faces = ["blue", "grey"]

[[pieces]]
pos = [90,100]
type = "Lib"
lib = "wikimedia"
item = "chess-w-N"
